name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - run: mkdir -p app 
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      uses: Borales/actions-yarn@v2.1.0
      with: 
        cmd: install
    - name: Build project
      uses: Borales/actions-yarn@v2.1.0
      with: 
        cmd: build > app
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Todo-list
        path: app
